name: jukebox
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.5
  - mpi4py=3.0.3
  - ipykernel
  - nb_conda
  - jupyter_contrib_nbextensions
  - nbdime
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - scikit-learn
  - yapf
  - isort